update
update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

update

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -7,14 +7,14 @@ function check_todo() {
   TODO_REGEX='// TODO'
   FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" | tr '\n' ' ')
   if [ -n "$FILES" ]; then
-      # Check for the TODO_REGEX in each staged .ts file
-      for FILE in $FILES; do
-          if grep -q "$TODO_REGEX" "$FILE"; then
-              echo "ERROR: Found 'TODO' reference in $FILE"
-              echo "Please remove 'TODO' comments before committing."
-              exit 1
-          fi
-      done
+    # Check for the TODO_REGEX in each staged .ts file
+    for FILE in $FILES; do
+      if grep -q "$TODO_REGEX" "$FILE"; then
+        echo "ERROR: Found 'TODO' reference in $FILE"
+        echo "Please remove 'TODO' comments before committing."
+        exit 1
+      fi
+    done
   fi
 }
 
